Numpy: numerical python
to perfrom mathematical operations


In [2]:
# create an array

import numpy as np

a=np.array([1,2,3,4])
type(a)


numpy.ndarray

In [4]:
a.dtype # type of data stored in array

dtype('int64')

In [18]:
# Import the timeit module and give it the alias 't'
import timeit as t

# Store a Python expression as a string.
# timeit() expects code as a string, so it can execute it repeatedly.
a = "14-54-5-6-5-42-3-3-5-6-7--3-5"

# Print the string exactly as it is stored
print(a)

# Execute the expression stored in 'a' many times and
# return the total execution time in seconds
print(t.timeit(a))

# Jupyter Notebook magic command
# Runs the expression many times and shows the average execution time
%timeit 1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

# Record the current high-precision time (start time)
b = t.default_timer()

# Code whose execution time we want to measure
1-1-1-1-1-1-1-1-1-1-1-111

# Record the current high-precision time again (end time)
c = t.default_timer()

# Calculate the elapsed time
# (end time - start time)
c - b

14-54-5-6-5-42-3-3-5-6-7--3-5
0.026749399956315756
21.5 ns ± 1.51 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


0.00010199984535574913

In [25]:
# creading different dimensions of arrays 


oneD=np.array([1,2,3,4])
print(oneD.ndim)
print(oneD)
twoD=np.array([[1,2,3],[4,5,6]])
print(twoD.ndim)
print(twoD)
threeD=np.array([[[1,2,3],[2,3,4],[4,5,6]]])
print(threeD.ndim)
print(threeD)

1
[1 2 3 4]
2
[[1 2 3]
 [4 5 6]]
3
[[[1 2 3]
  [2 3 4]
  [4 5 6]]]


In [28]:
# arrays filled with zeros,ones,empty 
a=np.zeros(4)
print(a)
b=np.zeros((2,2))
print(b)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [29]:
# ones

a=np.ones(4)
print(a)
b=np.ones((2,2))
print(b)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [35]:
# empty array 
# It does not fill the memory with zeros.
# Whatever data was already in that memory location is shown.

a=np.array([1,2,3,4])
b=np.empty((2,2))
print(a)
print(b)
a=np.array([[1,2],[3,4]])
b=np.empty((2,2))
print(b)

[1 2 3 4]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [36]:
# filling the elements

a=np.arange(4) 
print(a)

[0 1 2 3]


In [41]:
a=np.arange(2,3) # (START, STOP)
print(a)

# to create a 2 d array

a=np.arange(6).reshape(2,3)
print(a)

[2]
[[0 1 2]
 [3 4 5]]


In [44]:
# creating identical matrices 
print(np.eye(3))
print()
print(np.eye(3,4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [51]:
# to create evenly spaced arrays

print(np.linspace(0,10,5)) # ( np.linspace(start,end,count))

[ 0.   2.5  5.   7.5 10. ]


In [52]:
    # creating array with random elements 
