Numpy : Numerical python 



In [ ]:
# create a numpy array
import numpy as np

a=np.array([1,2,3,4])
print(a)
print(type(a))

In [ ]:
import timeit # to accurately measure the execution time of small code snippets 

a="5+5"
print(a)
print(timeit.timeit(a))

t1=timeit.default_timer()
a=1-23-4-5-6-34-23-354-64-63-3-4-45
t2=timeit.default_timer()
print(t2-t1)




In [ ]:
%timeit 5+5

In [ ]:
# different dimension arrays
oneD=np.array([1,2,3,4,5])
twoD=np.array([[1,2,3],[4,5,6]])
threeD=np.array([[[1,2],[2,3],[4,5]]])
print(oneD)
print(oneD.ndim)
print(twoD)
print(twoD.ndim)
print(threeD)
print(threeD.ndim)

In [ ]:
# array filled with zeros
zeros_1D=np.zeros(4)
print(zeros_1)

In [ ]:
zeros_2D=np.zeros((3,4))
print(zeros_2D)

In [ ]:
#arrays filled with one 
ones_1D=np.ones(4)
print(ones_1D)

In [ ]:
ones_2d=np.ones((3,4))
print(ones_2d)

In [ ]:
empty_2d=np.empty((3,4))
print(empty_2d)

In [ ]:
# fill elements 

arange_1=np.arange(4)
print(arange_1)


In [ ]:
arange_2=np.arange(3,8)
print(arange_2)

In [35]:
# array with diagonal elements 

diagonal_1=np.eye(3)
print(diagonal_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
diagonal_2=np.eye(3,5)
print(diagonal_2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [37]:
#evenly spaced array

ar_lin=np.linspace(0,10,5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# creating array with random elements


In [38]:
print(np.random.ranf((2,2)))

[[0.48724374 0.6748832 ]
 [0.65770299 0.91476248]]


In [39]:
print(np.random.rand(2,2))

[[0.8589763  0.02316966]
 [0.29961046 0.68600968]]


In [40]:
print(np.random.randint(0,10,size=(4,4)))

[[0 2 4 2]
 [1 7 4 4]
 [7 2 3 0]
 [7 2 4 2]]


# Datatypes

In [41]:
arr=np.array([1,2,3,4,5])

print(arr.dtype)

int32


In [42]:
print(arr.astype(np.float64)) #change numpy array datatype

[1. 2. 3. 4. 5.]


# changing numpy array shape


In [43]:
arr=np.random.randint(0,6,size=6)
print(arr)

[2 5 1 5 0 3]


In [44]:
print(arr)

[2 5 1 5 0 3]


In [45]:
brr=np.array([1,2,3,4],ndmin=2)
print(brr.shape)
print()
print(brr.reshape(2,2)) # change shape of the array 
print()
print(brr.shape)


(1, 4)

[[1 2]
 [3 4]]

(1, 4)


In [46]:
crr=np.array([1,2,3,4,5,6])
print(crr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


# numpy arthematic operations

In [47]:

a=np.array([1,2,3])
b=np.array([3,3,3])




print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))


[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]
[1 2 0]
[ 1  8 27]
[1 0 0]


In [48]:
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.cumsum(a))

1
3
0
2
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


## BroadCasting


In [49]:
u=np.array([1,2,3,4])
v=np.array([[1],[2],[3],[4]])
print(u)
print(u.shape)

print()
print(v)
print(v.shape)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [50]:
print(u+v)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [51]:
print(u*v)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## iterating

In [52]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)



[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [53]:
for i,d in np.ndenumerate(a):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 6
(2, 1) 7
(2, 2) 8


## copy vs view


In [54]:
a=np.array([1,2,3,4])
b=a.copy()
c=a.view()
print(a,b,c)




[1 2 3 4] [1 2 3 4] [1 2 3 4]


## join and split


In [55]:
a=np.array([1,2,3,4])
b=np.array([1,1,1,1])

print(np.concatenate((a,b),axis=0))


[1 2 3 4 1 1 1 1]


# Stack


In [56]:
a=np.array([1,2,3,4])
b=np.array([1,1,1,1])
print(np.stack((a,b),axis=0))

[[1 2 3 4]
 [1 1 1 1]]


# search / sort /filter


In [57]:
a=np.array([1,2,3,4])
print(np.where(a==2))

(array([1], dtype=int64),)


In [58]:
print(np.searchsorted(a,2,side='right'))

2


In [59]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[a>4])

[5 6 7 8 9]


In [60]:
print(a>2)


[False False  True  True  True  True  True  True  True]


In [61]:
a=np.array([[1,2],[2,3],[3,4]])
print(a.flatten())

[1 2 2 3 3 4]


# insert 


In [62]:
a=np.array([1,2,3,4,5,6])


In [63]:
a=np.insert(a,0,0)
print(a)

[0 1 2 3 4 5 6]


In [64]:
b=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b)
print()
print(np.insert(b,3,[4,4,4],axis=1)) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# matrices


In [65]:
a=np.matrix([[1,0,3],[2,1,4],[3,2,5]])
print(a)


[[1 0 3]
 [2 1 4]
 [3 2 5]]


In [66]:
print(np.swapaxes(a,0,1))

[[1 2 3]
 [0 1 2]
 [3 4 5]]


In [67]:
print(np.transpose(a))



[[1 2 3]
 [0 1 2]
 [3 4 5]]


## Linear Algebra

#### Matrix Multiplication   A@B, np.matmul(A,B), np.dot(A,B)

In [68]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [69]:
a@b

array([[19, 22],
       [43, 50]])

In [70]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [72]:
# Transpose 

a.T

array([[1, 3],
       [2, 4]])

In [73]:
# inverse of a matxi

np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [74]:
np.linalg.det(a)

-2.0000000000000004

In [75]:
# eigen values and eigen vectors

eigenValues,eigenVector = np.linalg.eig(a)
eigenValues, eigenVector




(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

#### What is SVD?

SVD (Singular Value Decomposition)

Definition:
SVD is a technique that breaks a dataset into hidden patterns and tells us which patterns are most important.

Formula:
A = U × S × Vt

Components:

1. Vt (Hidden Patterns)
   - Finds the hidden patterns in the data.
   - Answers: "What patterns exist?"

   Example:
   Pattern 1 → Science ability
   Pattern 2 → Language ability
   Pattern 3 → Creativity

2. S (Importance of Patterns)
   - Shows how important each pattern is.
   - Larger value = More important pattern.

   Example:
   [100, 20, 2]

   Pattern 1 → Very important
   Pattern 2 → Important
   Pattern 3 → Less important

3. U (Pattern Strength for Each Row)
   - Shows how much each row follows the patterns.
   - Answers: "Who follows these patterns?"

   Example:
   Student A → Strong science ability
   Student B → Medium science ability
   Student C → Weak science ability

Memory Trick:

Vt = What patterns exist?
S  = How important are they?
U  = Who follows those patterns?

Why SVD is Used:

- Dimensionality Reduction
- PCA
- Recommendation Systems
- Image Compression
- NLP / Topic Modeling
- Noise Removal

Simple Summary:

SVD finds hidden patterns in data, ranks them by importance,
and shows how strongly each data point follows those patterns.

## Solving Linear ALgebra

In [76]:
# Solve Ax = b
A = np.array([[2, 1], [5, 3]])
b = np.array([8, 23])

x = np.linalg.solve(A, b)
print(x)

[1. 6.]


In [78]:
M = np.array([[4, 2, 0],
              [2, 5, 1],
              [0, 1, 3]])

eigenvalue,eigenvector=np.linalg.eig(M)

print(np.linalg.det(M))
print(np.linalg.inv(M))
print(eigenvalue)

43.99999999999999
[[ 0.31818182 -0.13636364  0.04545455]
 [-0.13636364  0.27272727 -0.09090909]
 [ 0.04545455 -0.09090909  0.36363636]]
[6.73205081 2.         3.26794919]
