# NumPy Final Assessment (30 Questions)

**Instructions**
- Try without notes.
- Write answers in the code cells provided.
- Covers NumPy topics from your revision.


## Section A: Indexing & Slicing

Q1. Get the last 4 elements from `a=np.array([10,20,30,40,50,60,70,80,90,100])`.

In [46]:
import numpy as np
# Write your answer here
a=np.array([10,20,30,40,50,60,70,80,90,100])

print(a[-4:])

[ 70  80  90 100]


Q2. Get every alternate element starting from 20.

In [47]:
# Write your answer here
print(a[1::2])


[ 20  40  60  80 100]


Q3. What is the output of `a[::-1]`?

In [48]:
# Write your answer here
# answer : [100  90  80  70  60  50  40  30  20  10]

Q4. Get all elements except the first and last.

In [49]:
# Write your answer here

print(a[1:len(a)-1])

[20 30 40 50 60 70 80 90]


## Section B: Fancy Indexing

Q5. Write code to get `[10,50,100]`.

In [50]:
# Write your answer here
aa=np.array([10,50,100])
print(aa)

[ 10  50 100]


Q6. What is the output of `a[[5,2,0]]`?

In [51]:
# Write your answer here
print(a[[5,2,0]])

[60 30 10]


Q7. Explain the difference between `a[1:5]` and `a[[1,5]]`.

In [52]:
# Write your answer here
# a[1:5] prints elements from 1 to 5 
# a[[1,5]] prints elements at specific index 1,5

## Section C: Boolean Masking

Q8. Get all values greater than 60.

In [53]:
# Write your answer here
print(a[a>60])

[ 70  80  90 100]


Q9. Get all values between 30 and 80.

In [59]:
# Write your answer here
print(a[(a>30) & (a<80)])

[40 50 60 70]


Q10. Get all values less than 20 OR greater than 90.

In [61]:
# Write your answer here
print(a[(a<20) | (a>90)])

[ 10 100]


Q11. Get all even values.

In [63]:
# Write your answer here
print(a[(a%2==0)])

[ 10  20  30  40  50  60  70  80  90 100]


Q12. What is the output of `np.any(a > 95)`?

In [65]:
# Write your answer here
np.any(a > 95)

np.True_

Q13. What is the output of `np.all(a > 5)`?

In [66]:
# Write your answer here
np.all(a > 95)

np.False_

## Section D: Missing Values

Q14. What is the output of `np.isnan(a)` for `a=np.array([10,20,np.nan,40,50,np.nan])`?

In [70]:
# Write your answer here
a=np.array([10,20,np.nan,40,50,np.nan])
np.isnan(a)

array([False, False,  True, False, False,  True])

Q15. How many missing values exist?

# Write your answer here
#2
np.isnan(a).count

Q16. Why does `np.mean(a)` return `nan`?

In [74]:
# Write your answer here
np.mean(a) # because there are missing values ( nan ) in the array.

np.float64(nan)

Q17. Which function should be used instead?

In [75]:
# Write your answer here
np.nanmean(a)

np.float64(30.0)

## Section E: Array Operations

Q18. Difference between `flatten()` and `ravel()`.

In [18]:
# Write your answer here
#flatten -> returns copy
# ravel -> returns a view

Q19. Difference between `copy()` and `view()`.

In [76]:
# Write your answer here
# copy: standlaone thing original array not changed
# view: reference to the original and original array effected

Q20. What is broadcasting?

In [20]:
# Write your answer here
# matrix / array operations bewteen matrices of different dimensions 

## Section F: Join & Split

Q21. Output of `np.concatenate((a,b))` where a=[1,2,3], b=[4,5,6].

In [77]:
# Write your answer here
a=np.array([1,2,3])
b=np.array([4,5,6])
# np.concatenate((a,b)) => [1,2,3,4,5,6]

Q22. Output of `np.stack((a,b))`.

In [78]:
# Write your answer here
#[[1, 2, 3],[4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

Q23. Main difference between `concatenate()` and `stack()`.

In [79]:
# Write your answer here
# stack : vertical 
# concatenate : horizontal

## Section G: Statistics

Q24. Output of `np.mean([10,20,30,40,50])`.

In [80]:
# Write your answer here
np.mean([10,20,30,40,50])

np.float64(30.0)

Q25. Output of `np.cumsum([10,20,30,40,50])`.

In [81]:
# Write your answer here
np.cumsum([10,20,30,40,50])

array([ 10,  30,  60, 100, 150])

Q26. Difference between `np.max(a)` and `np.argmax(a)`.

In [26]:
# Write your answer here
# np.max(a) -> value of max element 
# np.argmax(a) -> index value of the max elemnt 

Q27. What does `np.var(a)` measure?

In [27]:
# Write your answer here
# gives out variance of the product 

## Section H: Linear Algebra

Q28. Difference between `np.dot()` and `*`.

In [88]:
# Write your answer here
b=[2,2,2]
np.dot(a,b) -> scalar wise 
a*b -> element wise 

array([2, 4, 6])

Q29. Why is matrix multiplication important in Machine Learning?

In [29]:
# Write your answer here
# to make predictions 
# to analyze large data sets 
# transforming and reducing data dimensions 

Q30. In one sentence, what is SVD used for?

In [30]:
# Write your answer here
# instead of reading the entire data sets we try to identify the patterns 

# Self Evaluation

| Topic | Score |
|---------|---------|
| Indexing & Slicing | /4 |
| Fancy Indexing | /3 |
| Boolean Masking | /6 |
| Missing Values | /4 |
| Array Operations | /3 |
| Join & Split | /3 |
| Statistics | /4 |
| Linear Algebra | /3 |

**Total: /30**
