Level 1: Array Creation & Basics


In [2]:
import numpy as np
# Create a 1Darray of numbers from 10 to 50 (inclusive).

a=np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
a=np.ones((3,3))
a*7

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [8]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a=np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Level 2: Indexing, Slicing & Shape


In [11]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr[1:2,:] # 2nd row

array([[4, 5, 6, 7]])

In [18]:
arr[:,3:] # last column

array([[ 3],
       [ 7],
       [11]])

In [20]:
arr[:2,:2]

array([[0, 1],
       [4, 5]])

In [21]:
#Create a 1D array of 20 random integers between 1 and 100. Then reshape it into a 4x5 matrix.


In [25]:
np.random.seed(122)
a=np.random.randint(1,100,size=20).reshape(4,5)
a

array([[27, 11, 55, 77, 63],
       [17, 16, 60, 99, 80],
       [63, 55, 43, 22, 32],
       [42, 71, 79, 36, 96]])

Level 3: Arithmetic, Broadcasting & Math

In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])



In [27]:
a+b

array([11, 22, 33, 44])

In [28]:
a-b

array([ -9, -18, -27, -36])

In [29]:
a*b

array([ 10,  40,  90, 160])

In [30]:
a/b

array([0.1, 0.1, 0.1, 0.1])

In [31]:
#Create a 1D array x = np.arange(5). Use broadcasting to add [[10], [20], [30]] to x.

x=np.arange(5)

In [32]:
x

array([0, 1, 2, 3, 4])

In [33]:
x+[[10],[20],[30]]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [34]:
arr = np.random.randint(0, 50, 10)

In [35]:
print(np.argmax(arr))

3


In [36]:
print(np.argmin(arr))


9


In [37]:
np.mean(arr)

22.0

In [38]:
np.std(arr)

12.545915670049755

Level 5: Joining, Splitting & Advanced

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [45]:
# Stack them vertically and horizontally (use vstack and hstack). 
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [46]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a=np.array([1,0,0,0,0,1])
b=np.vstack((a,a,a,a,a,a))
b



array([[1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1]])

In [58]:
a=np.array([[1,2],[3,4]])

In [62]:
a=np.array([1,2,3,4,5])
b=np.vstack((a,a+a,a+2*a,a+3*a,a+4*a))
b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])